name: Docs CI/CD Workflow
on:
  push:
    branches:
      - main
jobs:
  branch-main-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Clone repository microservice
        run: |
          git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/riccardovacirca/microservice.git microservice
      - name: Run unit-test
        run: cd microservice && chmod +x install.sh && ./install.sh --env-test && ./install.sh --test
